FROM nginx:1.27-alpine
COPY index.html /usr/share/nginx/html/index.html
COPY challenge.txt /usr/share/nginx/html/challenge.txt
COPY health.txt /usr/share/nginx/html/health.txt
COPY logo.png /usr/share/nginx/html/logo.png
